//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresar
    {
        public int id { get; set; }
        public string adresa { get; set; }
        public string grad { get; set; }
        public string opstina { get; set; }
        public Nullable<int> ptt { get; set; }
    }
}
