//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api_Pristup
    {
        public int api_sifra_korisnika { get; set; }
        public string api_naziv_korisnika { get; set; }
        public string api_username_korisnika { get; set; }
        public string api_lozinka_korisnika { get; set; }
        public Nullable<bool> rest_api { get; set; }
    }
}
