//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikal
    {
        public Artikal()
        {
            this.Stavke_Dokumenta = new HashSet<Stavke_Dokumenta>();
            this.Stavke_Isporuke = new HashSet<Stavke_Isporuke>();
            this.Zaliha_artikla = new HashSet<Zaliha_artikla>();
        }
    
        public int art_sifra { get; set; }
        public string art_naziv { get; set; }
        public string art_proizvodjac { get; set; }
        public string art_ean { get; set; }
        public Nullable<int> art_jedinica_mere { get; set; }
        public Nullable<int> kom_dobavljac { get; set; }
        public string art_tip { get; set; }
        public Nullable<bool> art_aktivan { get; set; }
    
        public virtual ICollection<Stavke_Dokumenta> Stavke_Dokumenta { get; set; }
        public virtual ICollection<Stavke_Isporuke> Stavke_Isporuke { get; set; }
        public virtual ICollection<Zaliha_artikla> Zaliha_artikla { get; set; }
    }
}
