//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacija_Korisnika
    {
        public Autorizacija_Korisnika()
        {
            this.Korisnik_Sistema = new HashSet<Korisnik_Sistema>();
        }
    
        public int atr_sifra { get; set; }
        public string atr_naziv { get; set; }
    
        public virtual ICollection<Korisnik_Sistema> Korisnik_Sistema { get; set; }
    }
}
