//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public Dokument()
        {
            this.Isporukas = new HashSet<Isporuka>();
            this.Stavke_Dokumenta = new HashSet<Stavke_Dokumenta>();
            this.Interni_Prenos = new HashSet<Interni_Prenos>();
        }
    
        public int dok_sifra_dokumenta { get; set; }
        public Nullable<int> tip_dokumenta { get; set; }
        public Nullable<System.DateTime> dok_datum_kreiranja { get; set; }
        public Nullable<int> dok_korisnik { get; set; }
        public Nullable<int> kom_komitent { get; set; }
        public Nullable<int> dok_veza { get; set; }
        public Nullable<int> pri_primalac { get; set; }
        public Nullable<int> psl_sifra_poslovnice { get; set; }
        public Nullable<System.DateTime> dok_datum_isporuke { get; set; }
        public string dok_napomena { get; set; }
        public string dok_broj_dokumenta { get; set; }
        public Nullable<bool> dok_otvoren { get; set; }
    
        public virtual Komitent Komitent { get; set; }
        public virtual Korisnik_Sistema Korisnik_Sistema { get; set; }
        public virtual Krajnji_Primalac Krajnji_Primalac { get; set; }
        public virtual Tip_Dokumenta Tip_Dokumenta1 { get; set; }
        public virtual ICollection<Isporuka> Isporukas { get; set; }
        public virtual ICollection<Stavke_Dokumenta> Stavke_Dokumenta { get; set; }
        public virtual ICollection<Interni_Prenos> Interni_Prenos { get; set; }
    }
}
