//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interni_Prenos
    {
        public int Id { get; set; }
        public int dok_sifra { get; set; }
        public int sa_poslovnice { get; set; }
        public int na_poslovnicu { get; set; }
        public Nullable<System.DateTime> datum_kreiranja { get; set; }
    
        public virtual Dokument Dokument { get; set; }
        public virtual Poslovnica Poslovnica { get; set; }
        public virtual Poslovnica Poslovnica1 { get; set; }
    }
}
