//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komitent
    {
        public Komitent()
        {
            this.Dokuments = new HashSet<Dokument>();
        }
    
        public int kom_sifra { get; set; }
        public string kom_naziv { get; set; }
        public string kom_adresa { get; set; }
        public string kom_grad { get; set; }
        public string kom_ptt { get; set; }
        public Nullable<bool> kom_dobavljac { get; set; }
        public Nullable<bool> kom_aktivan { get; set; }
        public string kom_PIB { get; set; }
        public string kom_MBR { get; set; }
    
        public virtual ICollection<Dokument> Dokuments { get; set; }
    }
}
