//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_VEM
    {
        public int log_id { get; set; }
        public string log_function { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string log_time { get; set; }
        public string log_message { get; set; }
        public Nullable<bool> log_isError { get; set; }
    }
}
