//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poslovnica
    {
        public Poslovnica()
        {
            this.Korisnik_Sistema = new HashSet<Korisnik_Sistema>();
            this.Rafs = new HashSet<Raf>();
            this.Zaliha_artikla = new HashSet<Zaliha_artikla>();
            this.Interni_Prenos = new HashSet<Interni_Prenos>();
            this.Interni_Prenos1 = new HashSet<Interni_Prenos>();
        }
    
        public int psl_sifra { get; set; }
        public string psl_naziv { get; set; }
        public Nullable<bool> psl_aktivna { get; set; }
    
        public virtual ICollection<Korisnik_Sistema> Korisnik_Sistema { get; set; }
        public virtual ICollection<Raf> Rafs { get; set; }
        public virtual ICollection<Zaliha_artikla> Zaliha_artikla { get; set; }
        public virtual ICollection<Interni_Prenos> Interni_Prenos { get; set; }
        public virtual ICollection<Interni_Prenos> Interni_Prenos1 { get; set; }
    }
}
