//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raf
    {
        public Raf()
        {
            this.Zaliha_artikla = new HashSet<Zaliha_artikla>();
        }
    
        public int raf_sifra { get; set; }
        public string raf_lokacija { get; set; }
        public Nullable<int> psl_poslovnica { get; set; }
    
        public virtual Poslovnica Poslovnica { get; set; }
        public virtual ICollection<Zaliha_artikla> Zaliha_artikla { get; set; }
    }
}
