//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_Dokumenta
    {
        public Nullable<int> dok_broj_dokumenta { get; set; }
        public Nullable<int> stv_sifra_artikla { get; set; }
        public Nullable<int> stv_kolicina { get; set; }
        public int stv_id { get; set; }
    
        public virtual Artikal Artikal { get; set; }
        public virtual Dokument Dokument { get; set; }
    }
}
