//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_Tovarnog_Lista
    {
        public Nullable<int> tl_broj { get; set; }
        public Nullable<int> isp_broj { get; set; }
        public int stv_id { get; set; }
    
        public virtual Isporuka Isporuka { get; set; }
        public virtual Tovarni_List Tovarni_List { get; set; }
    }
}
