//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_Dokumenta
    {
        public Tip_Dokumenta()
        {
            this.Dokuments = new HashSet<Dokument>();
        }
    
        public int tipdok_sifra { get; set; }
        public string tipdok_kratki_naziv { get; set; }
        public string tipdok_naziv { get; set; }
    
        public virtual ICollection<Dokument> Dokuments { get; set; }
    }
}
