//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovarni_List
    {
        public Tovarni_List()
        {
            this.Stavke_Tovarnog_Lista = new HashSet<Stavke_Tovarnog_Lista>();
        }
    
        public int tl_broj { get; set; }
        public Nullable<System.DateTime> tl_datum_kreiranja { get; set; }
        public Nullable<int> vzc_vozac { get; set; }
        public Nullable<bool> tl_zatvoren { get; set; }
    
        public virtual ICollection<Stavke_Tovarnog_Lista> Stavke_Tovarnog_Lista { get; set; }
        public virtual Vozac Vozac { get; set; }
    }
}
