//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM_API.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozac
    {
        public Vozac()
        {
            this.Tovarni_List = new HashSet<Tovarni_List>();
        }
    
        public int vzc_sifra { get; set; }
        public Nullable<int> kor_sifra { get; set; }
        public Nullable<int> vzl_sifra { get; set; }
    
        public virtual Korisnik_Sistema Korisnik_Sistema { get; set; }
        public virtual ICollection<Tovarni_List> Tovarni_List { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
